# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Networking_config = debug
endif
ifeq ($(config),release)
  Networking_config = release
endif
ifeq ($(config),dist)
  Networking_config = dist
endif

PROJECTS := Networking

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Networking:
ifneq (,$(Networking_config))
	@echo "==== Building Networking ($(Networking_config)) ===="
	@${MAKE} --no-print-directory -C . -f Networking.make config=$(Networking_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Networking.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Networking"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"